# 2.3 Blank Nodes

SELECT ?person ?university ?start ?end ?interval
WHERE {
    ?person :worksfor ?university .
    ?person :worksfor_p ?interval .
    ?interval :worksfor_ps ?university .
    ?interval :from ?start .
    ?interval :to ?end .
}
