# A_1 Diamondminus in rule body

SELECT ?person ?university ?start ?end
WHERE {
    ?person :recentlyEmployedBy ?university .
    ?person :recentlyEmployedBy_p ?interval .
    ?interval :recentlyEmployedBy_ps ?university .
    ?interval :from ?start .
    ?interval :to ?end .
}
