# A_1 Boxminus in rule body

SELECT ?person ?university ?interval ?start ?end
WHERE {
    ?person :recentlyEmployedBy ?university .
    ?person :recentlyEmployedBy_p ?interval .
    ?interval :recentlyEmployedBy_ps ?university .
    ?interval :from ?start .
    ?interval :to ?end .
}
