# A_1 Diamondplus in rule body

SELECT ?university ?person ?start ?end 
WHERE {
    ?university :willSoonEmploy ?person .
    ?university :willSoonEmploy_p ?interval .
    ?interval :willSoonEmploy_ps ?person .
    ?interval :from ?start .
    ?interval :to ?end .
}
